USE master
GO
IF DB_ID('HETHONGBANHANG_test') IS NOT NULL
	DROP DATABASE HETHONGBANHANG_test
GO 
CREATE DATABASE HETHONGBANHANG_test
GO

USE HETHONGBANHANG_test 

CREATE TABLE KHACHHANG
(
	ID INT IDENTITY(1,1),
	MAKHACHHANG AS 'KH' + RIGHT('000' + CAST(ID AS VARCHAR(3)), 3) PERSISTED,
	HOTEN NVARCHAR(40),
	TAIKHOAN CHAR(15),
	SODIENTHOAI CHAR(12),
	EMAIL CHAR(30),
	DIACHI NVARCHAR(50)
	--KHAI BAO KHOA CHINH
	CONSTRAINT PK_KH
	PRIMARY KEY (MAKHACHHANG)
)

CREATE TABLE SHOP
(
	ID INT IDENTITY(1,1),
	MASHOP AS 'SHOP' + RIGHT('000' + CAST(ID AS VARCHAR(3)), 3) PERSISTED,
	TENSHOP NVARCHAR(30),
	MACHUSHOP VARCHAR(5),
	DIACHI NVARCHAR(50),
	SODIENTHOAI CHAR(12),
	--KHAI BAO KHOA CHINH
	CONSTRAINT PK_SHOP
	PRIMARY KEY (MASHOP)
)
CREATE TABLE SANPHAM
(
	ID INT IDENTITY(1,1),
	MASANPHAM AS 'SP' + RIGHT('000' + CAST(ID AS VARCHAR(3)), 3) PERSISTED,
	TEN NVARCHAR(20),
	MAMATHANG VARCHAR(10),
	MASHOP VARCHAR(7),
	GIATIEN FLOAT,
	SOLUONGCONLAI INT,
	SOLUONGDABAN INT,	
	--KHAI BAO KHOA CHINH
	CONSTRAINT PK_SP
	PRIMARY KEY (MASANPHAM)
)
CREATE TABLE MATHANG
(
	ID INT IDENTITY(1,1),
	MAMATHANG AS 'MATHANG' + RIGHT('000' + CAST(ID AS VARCHAR(3)), 3) PERSISTED,
	TENMATHANG NVARCHAR(20)
	--KHAI BAO KHOA CHINH
	CONSTRAINT PK_MH
	PRIMARY KEY (MAMATHANG)
)
CREATE TABLE DONHANG
(
	ID INT IDENTITY(1,1),
	MADON AS 'DONHANG' + RIGHT('000' + CAST(ID AS VARCHAR(3)), 3) PERSISTED,
	MASANPHAM VARCHAR(5),
	MAKHACHHANG VARCHAR(5),
	NGAYLAPDON DATETIME,
	SOLUONG INT,
	TIENSHIP FLOAT,
	HINHTHUCTHANHTOAN NVARCHAR(30),
	--KHAI BAO KHOA CHINH
	CONSTRAINT PK_DH
	PRIMARY KEY (MADON)
)
CREATE TABLE GIAOHANG
(
	ID INT IDENTITY(1,1),
	MAGIAOHANG AS 'GH' + RIGHT('000' + CAST(ID AS VARCHAR(3)), 3) PERSISTED ,
	MADONHANG VARCHAR(10),
	MASHIPPER VARCHAR(6),
	TINHTRANGGIAO NVARCHAR(10),
	NGAYCAPNHAT DATETIME,
	--KHAI BAO KHOA CHINH
	CONSTRAINT PK_GH 
	PRIMARY KEY (MAGIAOHANG)
)

CREATE TABLE HOADON
(
	ID INT IDENTITY(1,1),
	MAHOADON AS 'HOADON' + RIGHT('000' + CAST(ID AS VARCHAR(3)), 3) PERSISTED,
	MAGIAOHANG VARCHAR(5),
	MAKHACHHANG VARCHAR(5),
	TINHTRANGHOADON NVARCHAR(20),
	TONGTIEN FLOAT,
	RATING CHAR(5),
	NHANXET NVARCHAR(30)
	--KHAI BAO KHOA CHINH
	CONSTRAINT PK_HD 
	PRIMARY KEY (MAHOADON)
)

CREATE TABLE SHIPPER
(	
	ID INT IDENTITY(1,1),
	MASHIPPER AS 'SHP' + RIGHT('000' + CAST(ID AS VARCHAR(3)), 3) PERSISTED,
	HOTEN NVARCHAR(40),
	TAIKHOAN CHAR(15),
	SODIENTHOAI CHAR(12),
	EMAIL CHAR(30),
	TENXE NVARCHAR(10),
	BIENSOXE CHAR(10),
	--KHAI BAO KHOA CHINH
	CONSTRAINT PK_SHP 
	PRIMARY KEY (MASHIPPER)
)
CREATE TABLE DANGNHAP
(
	TAIKHOAN CHAR(15),
	MATKHAU CHAR(15),
	LOAINGUOIDUNG CHAR(9)
	CONSTRAINT PK_DN
	PRIMARY KEY(TAIKHOAN)
)

-- KHAI BÁO RÀNG BUỘC KHÓA NGOẠI
--HOA DON VA GIAO HANG
ALTER TABLE HOADON ADD CONSTRAINT FK_HD_GH FOREIGN KEY(MAGIAOHANG) REFERENCES GIAOHANG ON DELETE CASCADE
--HOA DON VA KHACH HANG 
ALTER TABLE HOADON ADD CONSTRAINT FK_HD_KH FOREIGN KEY(MAKHACHHANG) REFERENCES KHACHHANG ON DELETE CASCADE
--GIAO HANG VA SHIPPER
ALTER TABLE GIAOHANG ADD CONSTRAINT FK_GH_SHP FOREIGN KEY(MASHIPPER) REFERENCES SHIPPER ON DELETE CASCADE
--GIAO HANG VOI DONHANG
ALTER TABLE GIAOHANG ADD CONSTRAINT FK_GH_DH FOREIGN KEY(MADONHANG) REFERENCES DONHANG ON DELETE CASCADE
--DON HANG VOI KHACHHANG 
ALTER TABLE DONHANG ADD CONSTRAINT FK_DH_KH FOREIGN KEY(MAKHACHHANG) REFERENCES KHACHHANG 
--DON HANG VOI SAN PHAM
ALTER TABLE DONHANG ADD CONSTRAINT FK_DH_SP FOREIGN KEY(MASANPHAM) REFERENCES SANPHAM ON DELETE CASCADE
--SHOP VOI KHACHHANG
ALTER TABLE SHOP ADD CONSTRAINT FK_SHOP_KH FOREIGN KEY(MACHUSHOP) REFERENCES KHACHHANG ON DELETE CASCADE
--SAN PHAM VOI MAT HANG
ALTER TABLE SANPHAM ADD CONSTRAINT FK_SP_MH FOREIGN KEY(MAMATHANG) REFERENCES MATHANG ON DELETE CASCADE
--SAN PHAM VOI SHOP 
ALTER TABLE SANPHAM ADD CONSTRAINT FK_SP_SHOP FOREIGN KEY(MASHOP) REFERENCES SHOP 
--TAI KHOAN VOI KHACHHANG
ALTER TABLE SHIPPER ADD CONSTRAINT PK_SHP_DN FOREIGN KEY(TAIKHOAN) REFERENCES DANGNHAP ON DELETE CASCADE
--TAI KHOAN VOI SHIPPER
ALTER TABLE KHACHHANG ADD CONSTRAINT PK_KH_DN FOREIGN KEY(TAIKHOAN) REFERENCES DANGNHAP 